var maxCountElements = 100;
var minSize = 30, maxSize = 300;
var faIcons = {
	'27': {winKey: 'Esc', icon: 'sign-language', sound: 'applause'},
	'112': {winKey: 'F1', icon: 'futbol-o', sound: 'ball-kick'},
	'113': {winKey: 'F2', icon: 'snapchat-ghost', sound: 'ghost'},
	'114': {winKey: 'F3', icon: 'car', sound: 'car'},
	'115': {winKey: 'F4', icon: 'volume-control-phone', sound: 'phone'},
	'116': {winKey: 'F5', icon: 'bell', sound: 'bell'},
	'117': {winKey: 'F6', icon: 'bomb', sound: 'bomb'},
	'118': {winKey: 'F7', icon: 'bicycle', sound: 'bicycle'},
	'119': {winKey: 'F8', icon: 'taxi', sound: 'police'},
	'120': {winKey: 'F9', icon: 'camera-retro', sound: 'camera-timer'},
	'121': {winKey: 'F10', icon: 'birthday-cake', sound: 'happy-birthday'},
	'122': {winKey: 'F11', icon: 'bolt', sound: 'bolt'},
	'123': {winKey: 'F12', icon: 'bus', sound: 'bus'},
	'145': {winKey: 'ScrollLock', icon: 'clock-o', sound: 'clock'},

	'192': {winKey: '~', icon: 'camera', sound: 'camera-auto'},
	'49': {winKey: '1', icon: 'child', sound: 'child'},
	'50': {winKey: '2', icon: 'cloud', sound: 'thunder'},
	'51': {winKey: '3', icon: 'coffee', sound: 'drink'},
	'52': {winKey: '4', icon: 'cutlery', sound: 'pour-food'},
	'53': {winKey: '5', icon: 'female', sound: 'laugh-woman'},
	'54': {winKey: '6', icon: 'fighter-jet', sound: 'plain'},
	'55': {winKey: '7', icon: 'fax', sound: 'phone-fax'},
	'56': {winKey: '8', icon: 'fire-extinguisher', sound: 'fire-extinguisher'},
	'57': {winKey: '9', icon: 'flag', sound: 'flag'},
	'48': {winKey: '0', icon: 'users', sound: 'noise-crowd'},
	'189': {winKey: '-', icon: 'heartbeat', sound: 'heartbeat'},
	'187': {winKey: '=', icon: 'gavel', sound: 'gavel'},
	'8': {winKey: 'Backspace', icon: 'magic', sound: 'magic'},
	'45': {winKey: 'Insert', icon: 'fire ', sound: 'fire'},
	'36': {winKey: 'Home', icon: 'cogs', sound: 'cogs'},
	'33': {winKey: 'PageUp', icon: 'gift', sound: 'magic2'},
	'144': {winKey: 'NumLock', icon: 'headphones', sound: 'rap'},
	'111': {winKey: '/', icon: 'key', sound: 'keys'},
	'106': {winKey: '*', icon: 'lock', sound: 'lock'},
	'109': {winKey: '-', icon: 'smile-o', sound: 'laugh'},

	'9': {winKey: 'Tab', icon: 'star', sound: 'magic3'},
	'81': {winKey: 'Q', icon: 'mobile', sound: 'mobile-vibra'},
	'87': {winKey: 'W', icon: 'motorcycle', sound: 'motorcycle'},
	'69': {winKey: 'E', icon: 'microphone', sound: 'microphone'},
	'82': {winKey: 'R', icon: 'life-ring', sound: 'help'},
	'84': {winKey: 'T', icon: 'print', sound: 'printer-matrix'},
	'89': {winKey: 'Y', icon: 'pencil', sound: 'pensil'},
	'85': {winKey: 'U', icon: 'rocket', sound: 'rocket'},
	'73': {winKey: 'I', icon: 'ship', sound: 'ship-alarm'},
	'79': {winKey: 'O', icon: 'subway', sound: 'subway'},
	'80': {winKey: 'P', icon: 'money', sound: 'cash'},
	'219': {winKey: '[', icon: 'scissors', sound: 'scissors'},
	'221': {winKey: ']', icon: 'eraser', sound: 'eraser'},
	'13': {winKey: 'Enter', icon: 'keyboard-o', sound: 'keyboard'},
	'46': {winKey: 'Delete', icon: 'file', sound: 'paper'},
	'35': {winKey: 'End', icon: 'meh-o', sound: 'oy'},
	'34': {winKey: 'PageDown', icon: 'users', sound: 'crowd'},
	'103': {winKey: '7', icon: 'newspaper-o', sound: 'paper'},
	'104': {winKey: '8', icon: 'paper-plane', sound: 'paper-cut'},
	'105': {winKey: '9', icon: 'laptop', sound: 'keyboard'},
	'107': {winKey: '+', icon: 'plug', sound: 'plug'},
	
	'20': {winKey: 'CapsLock', icon: 'university', sound: 'fanfars'},
	'65': {winKey: 'A', icon: 'calculator', sound: 'keyboard'},
	'83': {winKey: 'S', icon: 'book', sound: 'book'},
	'68': {winKey: 'D', icon: 'bug', sound: 'bug'},
	'70': {winKey: 'F', icon: 'bed', sound: 'snoring'},
	'71': {winKey: 'G', icon: 'bullhorn', sound: 'bullhorn'},
	'72': {winKey: 'H', icon: 'briefcase ', sound: 'icq'},
	'74': {winKey: 'J', icon: 'trophy', sound: 'fanfars2'},
	'75': {winKey: 'K', icon: 'calendar', sound: 'reminder'},
	'76': {winKey: 'L', icon: 'cube', sound: 'cubes-throw'},
	'186': {winKey: ':', icon: 'file-image-o', sound: 'people'},
	'222': {winKey: '\'', icon: 'graduation-cap', sound: 'fanfars2'},
	'220': {winKey: '\\', icon: 'tachometer', sound: 'car-brakes'},
	'100': {winKey: '4', icon: 'beer', sound: 'beer'},
	'101': {winKey: '5', icon: 'hand-peace-o', sound: 'people'},
	'102': {winKey: '6', icon: 'cubes', sound: 'cubes-throw'},
	'12': {winKey: 'empty-5', icon: 'comment', sound: 'icq'},

	'16': {winKey: 'Shift', icon: 'eye', sound: 'wow'},
	'226': {winKey: '\\', icon: 'leaf', sound: 'leafs'},
	'90': {winKey: 'Z', icon: 'paint-brush', sound: 'spray'},
	'88': {winKey: 'X', icon: 'thumbs-o-up', sound: 'yahoo'},
	'67': {winKey: 'C', icon: 'music', sound: 'fur-elise'},
	'86': {winKey: 'V', icon: 'paw', sound: 'cat'},
	'66': {winKey: 'B', icon: 'power-off', sound: 'switch'},
	'78': {winKey: 'N', icon: 'volume-up', sound: 'music'},
	'77': {winKey: 'M', icon: 'umbrella', sound: 'rain'},
	'188': {winKey: ',', icon: 'thumbs-o-down', sound: 'discontent'},
	'190': {winKey: '.', icon: 'tags', sound: 'cash'},
	'191': {winKey: '/', icon: 'wheelchair-alt', sound: 'scratch'},
	'38': {winKey: 'Up', icon: 'wrench', sound: 'repair'},
	'97': {winKey: '1', icon: 'google-wallet', sound: 'pensil'},
	'98': {winKey: '2', icon: 'linux', sound: 'pingvin'},
	'99': {winKey: '3', icon: 'tree', sound: 'leafs'},
	
    '17': {winKey: 'Ctrl', icon: 'ambulance', sound: 'ambulance'},
    '91': {winKey: 'RWin', icon: 'windows', sound: 'windows'},
    '18': {winKey: 'Alt', icon: 'dribbble', sound: 'basketball'},
    '32': {winKey: 'Space', icon: 'spinner fa-pulse', sound: 'spin'},
    '92': {winKey: 'LWin', icon: 'windows', sound: 'windows'},
    '93': {winKey: 'SubMenu', icon: 'crosshairs', sound: 'eshut'},
    '37': {winKey: 'Left', icon: 'trash', sound: 'trash'},
    '40': {winKey: 'Down', icon: 'user-secret', sound: 'din'},
    '39': {winKey: 'Right', icon: 'television', sound: 'footbal'},
    '96': {winKey: '0', icon: 'sun-o', sound: 'sun'},
    '110': {winKey: '.', icon: 'picture-o', sound: 'tada'}
};